nfd:
  enabled: false

daemonsets:
  tolerations:
    - operator: Exists
      effect: NoSchedule 

operator:
  resources:
    limits:
      cpu: null
      memory: 2Gi
  tolerations:
    - operator: Exists
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "node-role.kubernetes.io/control-plane"
                operator: Exists

driver:
  enabled: false
  version: "570.124.06"
  # env:
  # - name: http_proxy
  #   value: http://172.18.3.171:8080
  # - name: https_proxy
  #   value: http://172.18.3.171:8080
  # - name: no_proxy
  #   value: 127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,100.64.0.0/10,localhost
  rdma:
    enabled: false
    useHostMofed: false
  repoConfig:
    configMapName: repo-config
  # close GPU GSP (optional)
  kernelModuleConfig:
    name: "kernel-module-params"

toolkit:
  env:
    - name: CONTAINERD_SOCKET
      value: /run/k3s/containerd/containerd.sock
    - name: NVIDIA_CONTAINER_RUNTIME_LOG_LEVEL
      value: "warning"

dcgmExporter:
  enabled: true
  env:
    - name: DCGM_EXPORTER_LISTEN
      value: ":9400"
    - name: DCGM_EXPORTER_KUBERNETES
      value: "true"
  config:
    name: dcgm-exporter-config

migManager:
  enabled: false