apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-nvme0
provisioner: rancher.io/local-path
parameters:
  nodePath: /opt/local-nvme0
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
