apiVersion: v1
kind: ConfigMap
metadata:
  name: repo-config
  namespace: gpu-operator
data:
  custom-repo.list: |+
    deb [arch=amd64] http://repo.huaweicloud.com/ubuntu/ jammy main restricted
    deb [arch=amd64] http://repo.huaweicloud.com/ubuntu/ jammy-updates main restricted
  
    deb [arch=amd64] http://repo.huaweicloud.com/ubuntu/ jammy universe
    deb [arch=amd64] http://repo.huaweicloud.com/ubuntu/ jammy-updates universe
  
    deb [arch=amd64] http://repo.huaweicloud.com/ubuntu/ jammy multiverse
    deb [arch=amd64] http://repo.huaweicloud.com/ubuntu/ jammy-updates multiverse
  
    deb [arch=amd64] http://repo.huaweicloud.com/ubuntu/ jammy-backports main restricted universe multiverse
  
    deb [arch=amd64] http://repo.huaweicloud.com/ubuntu/ jammy-security main restricted
    deb [arch=amd64] http://repo.huaweicloud.com/ubuntu/ jammy-security universe
    deb [arch=amd64] http://repo.huaweicloud.com/ubuntu/ jammy-security multiverse
