apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: nccl-tests-nodes-ib
spec:
  slotsPerWorker: 8
  launcherCreationPolicy: WaitForWorkersReady
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - gn001
          containers:
            - image: ghcr.io/coreweave/nccl-tests:12.2.2-cudnn8-devel-ubuntu20.04-nccl2.19.3-1-3e0fbc3
              imagePullPolicy: Always
              name: nccl
              env:
                - name: OMPI_ALLOW_RUN_AS_ROOT
                  value: "1"
                - name: OMPI_ALLOW_RUN_AS_ROOT_CONFIRM
                  value: "1"
              # command: ["sleep", "infinity"]
              command: ["/bin/bash", "-c"]
              args: [
                  "mpirun \
                  -np 16 \
                  -bind-to none \
                  -x LD_LIBRARY_PATH \
                  -x NCCL_SOCKET_IFNAME=eth0 \
                  -x NCCL_IB_DISABLE=0 \ 
                  -x NCCL_IB_HCA=mlx5 \
                  -x NCCL_ALGO=Ring \
                  -x NCCL_IB_QPS_PER_CONNECTION=4 \
                  /opt/nccl_tests/build/all_reduce_perf -b 8 -e 8g -f 2 -g 1 \
                  ",
                ]
                  # -x NCCL_CROSS_NIC=1 \
                  # -x NCCL_DEBUG=INFO \
                  # -x NCCL_DEBUG_SUBSYS=ALL \
                  # -x NCCL_LAUNCH_MODE=GROUP \
                  # /opt/nccl_tests/build/alltoall_perf -b 8 -e 8G -f 2 -g 1 \
              resources:
                requests:
                  cpu: 2
                  memory: 128Mi
          tolerations:
            - operator: Exists
              effect: NoSchedule
          enableServiceLinks: false
          automountServiceAccountToken: false
    Worker:
      replicas: 2
      template:
        metadata:
          labels:
            job: nccl-test
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - gn001
                      - gn002
          containers:
            - image: ghcr.io/coreweave/nccl-tests:12.2.2-cudnn8-devel-ubuntu20.04-nccl2.19.3-1-3e0fbc3
              imagePullPolicy: Always
              name: nccl
              resources:
                limits:
                  cpu: 80
                  memory: 100Gi
                  nvidia.com/gpu: 8
                  rdma/hca: 1
              volumeMounts:
                - mountPath: /dev/shm
                  name: dshm
              securityContext:
                capabilities: 
                  add: 
                    - IPC_LOCK
          volumes:
            - emptyDir:
                medium: Memory
              name: dshm
          tolerations:
            - operator: Exists
              effect: NoSchedule
          enableServiceLinks: false
          automountServiceAccountToken: false
